#if UNITY_EDITOR
#if GASKELLGAMES
using System.Collections.Generic;
using Gaskellgames.EditorOnly;
using UnityEditor;
using UnityEngine;

namespace Gaskellgames.FolderSystem.EditorOnly
{
    /// <remarks>
    /// Code created by Gaskellgames: https://gaskellgames.com
    /// </remarks>

    [CreateAssetMenu(fileName = "FolderIconSettings", menuName = "Gaskellgames/Folder System/FolderIconSettingsSO")]
    public class FolderSystemSettings_SO : GgScriptableObject
    {
        #region Variables

        internal enum SelectedState
        {
            Off,
            AutoGenerated,
            UserGenerated
        }

        [SerializeField, ReadOnly]
        internal bool defaultFolderIcons = false;
        
        [SerializeField, ReadOnly]
        private SelectedState projectFolderState = SelectedState.AutoGenerated;
        
        internal SelectedState ProjectFolderState
        {
            get => projectFolderState;
            set
            {
                projectFolderState = value;
                CreateFolderIconDictionary();
            }
        }

        [SerializeField, ReadOnly]
        private SerializedDictionary<string, Texture> userGeneratedLinks;
        
        internal Dictionary<string, Texture> folderIconDictionary { get; private set; }
        
        private const string packageRefName = "FolderSystem";
        private const string relativePath = "/Editor/Data/";
        private const string fileName = "FolderSystemSettings";

        #endregion
        
        //----------------------------------------------------------------------------------------------------
        
        #region Internal Methods
        
        private static FolderSystemSettings_SO instance;
        
        internal static FolderSystemSettings_SO Instance
        {
            get
            {
                if (!instance)
                {
                    instance = ScriptableObjectExtensions.GetEditorInstance<FolderSystemSettings_SO>(packageRefName, relativePath, fileName);
                }
                return instance;
            }
        }
        
        internal void Initialise()
        {
            ProjectFolderIcons.AutoGenerateIconDictionary();
            CleanUserGeneratedLinks();
            CreateFolderIconDictionary();
        }
        
        internal void ResetUserGeneratedLinks()
        {
            ProjectFolderIcons.AutoGenerateIconDictionary();
            userGeneratedLinks = new SerializedDictionary<string, Texture>(ProjectFolderIcons.autoGeneratedIconDictionary);
            EditorUtility.SetDirty(this);
        }
        
        internal void CleanUserGeneratedLinks()
        {
            if (userGeneratedLinks.ClearInvalidEntries())
            {
                EditorUtility.SetDirty(this);
            }
        }
        
        internal bool TryAddToUserGeneratedLinks(string key, Texture value)
        {
            if (!userGeneratedLinks.TryAdd(key, value)) { return false; }
            EditorUtility.SetDirty(this);
            return true;
        }
        
        internal bool RemoveFromUserGeneratedLinks(string key)
        {
            if (!userGeneratedLinks.Remove(key)) { return false; }
            EditorUtility.SetDirty(this);
            return true;
        }
        
        internal bool TryGetKeysForValue(Texture image, out List<string> keys)
        {
            return userGeneratedLinks.TryGetKeysForValue(image, out keys);
        }
        
        internal void CreateFolderIconDictionary()
        {
            folderIconDictionary = new Dictionary<string, Texture>();
            switch (projectFolderState)
            {
                case SelectedState.AutoGenerated:
                    ProjectFolderIcons.AutoGenerateIconDictionary();
                    folderIconDictionary = ProjectFolderIcons.autoGeneratedIconDictionary;
                    break;
                
                case SelectedState.UserGenerated:
                    folderIconDictionary = userGeneratedLinks.ToDictionary();
                    break;
                
                case SelectedState.Off:
                default:
                    break;
            }
        }
        
        #endregion
        
    } // class end
}
#endif
#endif